# Generated by Django 4.0.3 on 2022-04-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='email',
        ),
    ]
