# Generated by Django 4.0.3 on 2022-04-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_profileuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='application.department'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='application.department'),
        ),
    ]
